import { colors, fonts } from '@doan-labs/duo-uikit/tokens.stylex.ts'
import * as stylex from '@stylexjs/stylex'

const pulse = stylex.keyframes({ '0%': { opacity: 0.6 }, '50%': { opacity: 1 }, '100%': { opacity: 0.6 } })
const rise = stylex.keyframes({ from: { transform: 'translateY(100%)' }, to: { transform: 'translateY(0)' } })
const drop = stylex.keyframes({ from: { transform: 'translateY(-140%)' }, to: { transform: 'translateY(0)' } })
const glow = stylex.keyframes({
  '0%': { boxShadow: '0 0 0 0 rgba(255,255,255,.9)' },
  '100%': { boxShadow: '0 0 0 14px rgba(255,255,255,0)' }
})

export const styles = stylex.create({
  root: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
    color: colors.white,
    backgroundColor: colors.black,
    fontFamily: fonts.system,
    fontSize: 14,
    userSelect: 'none',
    touchAction: 'manipulation',
    cursor: 'pointer'
  },
  // The platform reset hides `canvas` until the shell marks the body ready; this app owns its canvas.
  canvas: { position: 'absolute', top: 0, left: 0, display: 'block', opacity: 1, cursor: 'pointer' },
  size: (w: number, h: number) => ({ width: `${w}px`, height: `${h}px` }),
  hud: {
    position: 'absolute',
    top: 10,
    left: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    fontSize: 12,
    fontWeight: 700,
    textShadow: '0 1px 6px rgba(20,60,120,.5)',
    pointerEvents: 'none'
  },
  hudCover: { top: 6, left: 8, fontSize: 10 },
  hudDim: { opacity: 0.8, fontWeight: 500 },
  intro: {
    position: 'absolute',
    insetInline: 0,
    top: '10%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
    textAlign: 'center',
    paddingInline: 16,
    pointerEvents: 'none',
    textShadow: '0 2px 12px rgba(20,60,120,.5)'
  },
  introCover: { top: '6%', gap: 3 },
  kicker: { fontSize: 10, fontWeight: 700, letterSpacing: 2, opacity: 0.9 },
  title: { marginBlock: 0, fontSize: 48, lineHeight: 1, fontWeight: 800, letterSpacing: -1.5 },
  titleCover: { fontSize: 30 },
  line: { marginBlock: 0, fontSize: 14, fontWeight: 600 },
  lineCover: { fontSize: 12 },
  best: { marginBlock: 0, fontSize: 12, fontWeight: 600, opacity: 0.95 },
  tap: {
    marginTop: 8,
    paddingBlock: 6,
    paddingInline: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,.25)',
    backdropFilter: 'blur(8px)',
    fontSize: 12,
    fontWeight: 700,
    textShadow: 'none',
    animationName: pulse,
    animationDuration: '1.4s',
    animationIterationCount: 'infinite'
  },
  toast: {
    position: 'absolute',
    insetInline: 0,
    top: '24%',
    marginInline: 'auto',
    width: 'fit-content',
    maxWidth: '80%',
    paddingBlock: 6,
    paddingInline: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,.85)',
    color: '#0b1a3a',
    fontSize: 13,
    fontWeight: 700,
    textAlign: 'center',
    pointerEvents: 'none',
    boxShadow: '0 6px 20px rgba(20,60,120,.25)'
  },
  toastCover: { fontSize: 11, top: '28%' },
  alert: {
    position: 'absolute',
    insetInline: 16,
    top: '50%',
    transform: 'translateY(-50%)',
    marginInline: 'auto',
    maxWidth: 340,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    paddingBlock: 16,
    paddingInline: 16,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,.88)',
    backdropFilter: 'blur(18px)',
    color: '#0b1a3a',
    textAlign: 'center',
    boxShadow: '0 16px 48px rgba(20,60,120,.35)'
  },
  alertCover: { insetInline: 8, gap: 4, paddingBlock: 10, paddingInline: 10, borderRadius: 16 },
  alertTitle: { fontSize: 17, fontWeight: 700 },
  roast: { marginBlock: 0, fontSize: 14, fontWeight: 600, lineHeight: 1.3 },
  fine: { marginBlock: 0, fontSize: 11, color: '#5b6b85' },
  link: {
    borderWidth: 0,
    padding: 0,
    backgroundColor: 'transparent',
    color: '#c0392b',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: fonts.system
  },
  stats: { display: 'flex', gap: 6, flexWrap: 'wrap', justifyContent: 'center' },
  stat: {
    minWidth: 62,
    paddingBlock: 6,
    paddingInline: 10,
    borderRadius: 10,
    color: '#5b6b85',
    backgroundColor: 'rgba(20,60,120,.08)',
    fontSize: 8,
    letterSpacing: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 2
  },
  value: { color: '#0b1a3a', fontSize: 18, fontWeight: 800, letterSpacing: 0 },
  medalValue: { fontSize: 12 },
  actions: { display: 'flex', gap: 6, flexWrap: 'wrap', justifyContent: 'center' },
  button: {
    borderWidth: 0,
    borderRadius: 999,
    paddingBlock: 8,
    paddingInline: 14,
    color: colors.white,
    backgroundColor: colors.blueBright,
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer'
  },
  secondary: { color: '#0b1a3a', backgroundColor: 'rgba(20,60,120,.1)' },
  // ---- the pay sheet ----
  dim: { position: 'absolute', inset: 0, backgroundColor: 'rgba(0,0,0,.35)' },
  sheet: {
    position: 'absolute',
    insetInline: 0,
    bottom: 0,
    marginInline: 'auto',
    maxWidth: 420,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    paddingBlock: 14,
    paddingInline: 18,
    paddingBottom: 22,
    borderStartStartRadius: 24,
    borderStartEndRadius: 24,
    backgroundColor: 'rgba(255,255,255,.96)',
    color: '#0b1a3a',
    fontSize: 13,
    boxShadow: '0 -12px 40px rgba(0,0,0,.25)',
    animationName: rise,
    animationDuration: '.32s',
    animationTimingFunction: 'cubic-bezier(.2,.8,.2,1)'
  },
  sheetCover: { fontSize: 11, gap: 4, paddingBlock: 8, paddingBottom: 12, paddingInline: 12 },
  sheetHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingBottom: 4 },
  payMark: { fontSize: 17, fontWeight: 600, letterSpacing: -0.3 },
  apple: { fontFamily: '-apple-system, "SF Pro", system-ui', fontWeight: 400 },
  cancel: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: colors.blueBright,
    fontSize: 15,
    fontWeight: 400,
    cursor: 'pointer',
    fontFamily: fonts.system
  },
  cardRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    paddingBlock: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(60,60,67,.18)'
  },
  card: {
    flexShrink: 0,
    width: 36,
    height: 24,
    borderRadius: 4,
    backgroundImage: 'linear-gradient(135deg, #e5484d, #b3261e)',
    boxShadow: 'inset 0 0 0 1px rgba(0,0,0,.08)'
  },
  cardText: { flex: 1, display: 'flex', flexDirection: 'column', fontSize: 12, lineHeight: 1.2, color: '#0b1a3a' },
  chev: { color: '#c7c7cc', fontSize: 22, lineHeight: 1 },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingBlock: 9,
    paddingLeft: 48,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(60,60,67,.18)'
  },
  last: { borderBottomWidth: 0 },
  rowKey: { color: '#8a8a8e', fontSize: 11, fontWeight: 500, letterSpacing: 0.4 },
  rowValue: { fontSize: 12, fontWeight: 500 },
  faceId: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    marginTop: 6,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    color: '#0b1a3a',
    cursor: 'pointer',
    fontFamily: fonts.system
  },
  faceLabel: { fontSize: 13, fontWeight: 500 },
  sideHint: {
    marginTop: 2,
    fontSize: 11,
    color: '#8a8a8e',
    animationName: pulse,
    animationDuration: '1.2s',
    animationIterationCount: 'infinite'
  },
  check: {
    display: 'inline-flex',
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1f8f4e',
    color: colors.white,
    fontSize: 24
  },
  sideButton: {
    position: 'absolute',
    right: 0,
    top: '8%',
    width: 18,
    height: '27%',
    borderWidth: 0,
    borderStartStartRadius: 10,
    borderEndStartRadius: 10,
    backgroundImage: 'linear-gradient(90deg, #4a4b55, #1d1e26)',
    cursor: 'pointer',
    animationName: glow,
    animationDuration: '1.1s',
    animationIterationCount: 'infinite'
  },
  // ---- the notification after paying ----
  notice: {
    position: 'absolute',
    top: 10,
    insetInline: 0,
    marginInline: 'auto',
    width: 'min(92%, 380px)',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    paddingBlock: 10,
    paddingInline: 12,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,.94)',
    color: '#0b1a3a',
    fontSize: 13,
    boxShadow: '0 10px 30px rgba(20,60,120,.3)',
    animationName: drop,
    animationDuration: '.4s',
    animationTimingFunction: 'cubic-bezier(.2,.8,.2,1)',
    pointerEvents: 'none'
  },
  noticeCover: { fontSize: 11, paddingBlock: 6, gap: 6 },
  noticeIcon: {
    flexShrink: 0,
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundImage: 'linear-gradient(135deg, #1d5fa8, #8be7ff)'
  },
  noticeText: { display: 'flex', flexDirection: 'column', gap: 1, flex: 1, minWidth: 0 },
  noticeTime: { alignSelf: 'flex-start', fontSize: 11, color: '#8a95a8' }
})
