/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as BuildRouteImport } from './routes/build'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as KitRouteImport } from './routes/kit'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as DocsSdkRouteImport } from './routes/docs.sdk'
import { Route as KitIndexRouteImport } from './routes/kit.index'
import { Route as KitNameRouteImport } from './routes/kit.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSdkRoute = DocsSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => DocsRoute,
} as any)
const KitIndexRoute = KitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitRoute,
} as any)
const KitNameRoute = KitNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => KitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/build': typeof BuildRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/guidelines': typeof GuidelinesRoute
  '/kit': typeof KitRouteWithChildren
  '/publish': typeof PublishRoute
  '/sdk': typeof SdkRoute
  '/simulator': typeof SimulatorRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/kit/$name': typeof KitNameRoute
  '/docs/': typeof DocsIndexRoute
  '/kit/': typeof KitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/build': typeof BuildRoute
  '/changelog': typeof ChangelogRoute
  '/get-started': typeof GetStartedRoute
  '/guidelines': typeof GuidelinesRoute
  '/publish': typeof PublishRoute
  '/sdk': typeof SdkRoute
  '/simulator': typeof SimulatorRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/kit/$name': typeof KitNameRoute
  '/docs': typeof DocsIndexRoute
  '/kit': typeof KitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/build': typeof BuildRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/guidelines': typeof GuidelinesRoute
  '/kit': typeof KitRouteWithChildren
  '/publish': typeof PublishRoute
  '/sdk': typeof SdkRoute
  '/simulator': typeof SimulatorRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/kit/$name': typeof KitNameRoute
  '/docs/': typeof DocsIndexRoute
  '/kit/': typeof KitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/build'
    | '/changelog'
    | '/docs'
    | '/get-started'
    | '/guidelines'
    | '/kit'
    | '/publish'
    | '/sdk'
    | '/simulator'
    | '/docs/$'
    | '/docs/sdk'
    | '/kit/$name'
    | '/docs/'
    | '/kit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/build'
    | '/changelog'
    | '/get-started'
    | '/guidelines'
    | '/publish'
    | '/sdk'
    | '/simulator'
    | '/docs/$'
    | '/docs/sdk'
    | '/kit/$name'
    | '/docs'
    | '/kit'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/build'
    | '/changelog'
    | '/docs'
    | '/get-started'
    | '/guidelines'
    | '/kit'
    | '/publish'
    | '/sdk'
    | '/simulator'
    | '/docs/$'
    | '/docs/sdk'
    | '/kit/$name'
    | '/docs/'
    | '/kit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  BuildRoute: typeof BuildRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  GuidelinesRoute: typeof GuidelinesRoute
  KitRoute: typeof KitRouteWithChildren
  PublishRoute: typeof PublishRoute
  SdkRoute: typeof SdkRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sdk': {
      id: '/docs/sdk'
      path: '/sdk'
      fullPath: '/docs/sdk'
      preLoaderRoute: typeof DocsSdkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/kit/': {
      id: '/kit/'
      path: '/'
      fullPath: '/kit/'
      preLoaderRoute: typeof KitIndexRouteImport
      parentRoute: typeof KitRoute
    }
    '/kit/$name': {
      id: '/kit/$name'
      path: '/$name'
      fullPath: '/kit/$name'
      preLoaderRoute: typeof KitNameRouteImport
      parentRoute: typeof KitRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsSdkRoute: typeof DocsSdkRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsSdkRoute: DocsSdkRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface KitRouteChildren {
  KitNameRoute: typeof KitNameRoute
  KitIndexRoute: typeof KitIndexRoute
}

const KitRouteChildren: KitRouteChildren = {
  KitNameRoute: KitNameRoute,
  KitIndexRoute: KitIndexRoute,
}

const KitRouteWithChildren = KitRoute._addFileChildren(KitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  BuildRoute: BuildRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  GuidelinesRoute: GuidelinesRoute,
  KitRoute: KitRouteWithChildren,
  PublishRoute: PublishRoute,
  SdkRoute: SdkRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
