import { createHash } from 'node:crypto'
import { resolve } from 'node:path'
import { stylexPlugin } from '../../../stylex-plugin'

const root = resolve(import.meta.dir, '../../..')
const output = resolve(import.meta.dir, '../public/builder')
const adapter = resolve(root, 'packages/uikit/sandbox-stylex.ts')
const sx = stylexPlugin(false)
const build = await Bun.build({
  entrypoints: [resolve(import.meta.dir, 'builder-runtime.ts')],
  target: 'browser',
  format: 'esm',
  minify: true,
  define: { 'process.env.NODE_ENV': '"production"' },
  plugins: [
    sx.plugin,
    {
      name: 'builder-stylex',
      setup(build) {
        build.onResolve({ filter: /^@stylexjs\/stylex$/ }, (args) => ({
          path: args.importer === adapter ? Bun.resolveSync('@stylexjs/stylex', resolve(root, 'packages/web')) : adapter
        }))
        build.onResolve({ filter: /^(react|react-dom)(\/.*)?$/ }, (args) => ({
          path: Bun.resolveSync(args.path, resolve(root, 'packages/web'))
        }))
      }
    }
  ]
})
if (!build.success) throw new AggregateError(build.logs, 'Builder runtime failed')
let js = await build.outputs[0].text()
let css = sx.css()
for (const url of new Set((js + css).match(/\/(?:icons|fonts)\/[a-zA-Z0-9._/-]+\.(?:webp|png|woff2?|ttf)/g) ?? [])) {
  const file = Bun.file(resolve(root, `public${url}`))
  if (!(await file.exists())) throw new Error(`Missing builder asset ${url}`)
  const data = `data:${file.type};base64,${Buffer.from(await file.arrayBuffer()).toString('base64')}`
  js = js.replaceAll(url, data)
  css = css.replaceAll(url, data)
}
await Bun.write(resolve(output, 'runtime.js'), js)
const runtime = await import(resolve(output, 'runtime.js'))
const modules = {
  react: 'react',
  'react-dom': 'reactDom',
  'react-dom/client': 'reactClient',
  'react/jsx-runtime': 'jsx',
  '@doan-labs/duo-sdk': 'sdk',
  '@doan-labs/duo-sdk/react': 'sdkReact',
  '@doan-labs/duo-uikit': 'kit',
  '@doan-labs/duo-uikit/tokens.stylex': 'tokens',
  '@stylexjs/stylex': 'stylex'
}
const files = { 'runtime.js': js }
for (const [name, key] of Object.entries(modules)) {
  const exports = Object.keys(runtime[key]).filter((key) => key !== 'default' && /^[a-zA-Z_$][\w$]*$/.test(key))
  files[name] =
    `import {${key} as mod} from 'duo-runtime'; export const {${exports.join(',')}} = mod; export default mod.default ?? mod;`
}
const reset = (await Bun.file(resolve(root, 'packages/shell/index.html')).text()).match(/<style>([\s\S]*?)<\/style>/)[1]
const api = await Bun.file(resolve(root, 'docs/platform/api/uikit.json')).json()
const descriptor = JSON.stringify({
  files,
  css: reset + css,
  tokens: runtime.tokens,
  sdk: (await Bun.file(resolve(root, 'packages/sdk/package.json')).json()).version,
  kit: (await Bun.file(resolve(root, 'packages/uikit/package.json')).json()).version,
  api
})
const hash = createHash('sha256').update(descriptor).digest('hex').slice(0, 16)
const compilerVersion = (
  await Bun.file(Bun.resolveSync('esbuild-wasm/package.json', resolve(root, 'packages/web'))).json()
).version
const runtimeURL = `/builder/runtime-${hash}.json`
const wasmURL = `/builder/esbuild-${compilerVersion}.wasm`
await Bun.write(resolve(output, runtimeURL.split('/').pop()), descriptor)
await Bun.write(
  resolve(output, wasmURL.split('/').pop()),
  Bun.file(Bun.resolveSync('esbuild-wasm/esbuild.wasm', resolve(root, 'packages/web')))
)
await Bun.write(
  resolve(import.meta.dir, '../src/generated/builder-assets.ts'),
  `// Generated by scripts/builder-assets.mjs.\nexport const runtimeURL = '${runtimeURL}'\nexport const wasmURL = '${wasmURL}'\n`
)
console.log(`Builder runtime: ${Math.round(js.length / 1024)} KiB JS, ${Math.round(css.length / 1024)} KiB CSS`)
