// The curated catalog the hosted Store loads at /catalog/index.json: the immutable
// release tree published to the `catalog` branch, plus the bundled Notes and Weather
// releases the root build wrote to dist/cdn, merged by the same publisher CI uses.
// Without the branch (a fresh fork, offline) the bundled releases alone are served.
import { spawnSync } from 'node:child_process'
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { publish } from '../../../scripts/publish-catalog.ts'
import { type Catalog, type Release, releaseId } from '../../sdk/manifest.ts'
import { PERMISSIONS } from '../../sdk/permissions.ts'

const root = fileURLToPath(new URL('../../../', import.meta.url))
const here = fileURLToPath(new URL('../', import.meta.url))
const target = `${here}public/catalog`
rmSync(target, { recursive: true, force: true })
mkdirSync(target, { recursive: true })
const fetched = spawnSync('git', ['fetch', '--depth=1', 'origin', 'catalog'], { cwd: root, stdio: 'ignore' })
if (fetched.status === 0) {
  const archive = spawnSync('sh', ['-c', `git archive origin/catalog | tar -x -C "${target}"`], {
    cwd: root,
    stdio: 'inherit'
  })
  if (archive.status !== 0) {
    console.error('catalog: could not unpack origin/catalog')
    process.exit(archive.status ?? 1)
  }
  console.log('catalog: unpacked the catalog branch')
} else console.log('catalog: no catalog branch reachable; serving the bundled releases only')
const result = await publish(`${root}dist/cdn`, target)
console.log(
  `catalog: ${result.published.length} bundled releases added, ${result.reused.length} reused → public/catalog/`
)

// The shelf on / and /apps reads the same index the Store installs from, so the site
// never lists an app that is not actually published.
const index: Catalog = JSON.parse(readFileSync(`${target}/index.json`, 'utf8'))
const shelf = Object.entries(index.apps).map(([id, app]) => {
  const releases = app.releases.map(
    ({ release }): Release => JSON.parse(readFileSync(`${target}/apps/${id}/${release}/release.json`, 'utf8'))
  )
  const newest = releases[0]!
  const dates = releases.map((r) => r.build.at).sort()
  return {
    id,
    name: app.name,
    author: app.author,
    lane: app.lane,
    repo: app.repo,
    version: newest.manifest.version,
    releases: releases.length,
    created: dates[0]!,
    updated: dates.at(-1)!,
    permissions: (app.permissions ?? []).map((name) => ({ name, label: PERMISSIONS[name].label })),
    icon: `/catalog/apps/${id}/${releaseId(newest)}/icon-1024.png`
  }
})
const generated = `${here}src/generated/catalog.ts`
writeFileSync(
  generated,
  [
    '// Generated by scripts/catalog.ts from public/catalog/index.json. Do not edit.',
    'export type CatalogApp = {',
    '  id: string',
    '  name: string',
    '  author: string',
    "  lane: 'official' | 'community'",
    '  repo: string',
    '  version: string',
    '  releases: number',
    '  created: string',
    '  updated: string',
    '  permissions: { name: string; label: string }[]',
    '  icon: string',
    '}',
    `export const CATALOG: CatalogApp[] = ${JSON.stringify(shelf, null, 2)}`,
    ''
  ].join('\n')
)
console.log(`catalog: ${shelf.length} apps → src/generated/catalog.ts`)
