// Writes src/generated/tokens.ts from packages/uikit/tokens.stylex.ts so the
// guidelines page can print the real hex and the real TSDoc. It has to be
// generated: `colors`, `fonts` and `app` are `defineVars`, whose runtime value
// is a `var(--x)` reference and never the colour itself. Parsed with the Babel
// parser the StyleX plugin already brings, like scripts/api.ts.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parseSync, type types as t } from '@babel/core'

const SOURCE = 'packages/uikit/tokens.stylex.ts'

const root = fileURLToPath(new URL('../../../', import.meta.url))
const code = readFileSync(root + SOURCE, 'utf8')
const ast = parseSync(code, {
  filename: root + SOURCE,
  babelrc: false,
  configFile: false,
  parserOpts: { plugins: ['typescript'] }
})
if (ast?.type !== 'File') throw new Error(`cannot parse ${SOURCE}`)

/** The comment directly above a key, stripped of its `*` gutter. */
function doc(node: t.Node): string {
  const c = node.leadingComments?.at(-1)
  if (!c) return ''
  return c.value
    .split('\n')
    .map((l) => l.replace(/^\s*\*+\s?/, '').trimEnd())
    .join('\n')
    .trim()
}

/** Every value in this file is a literal; anything else is printed as written. */
function value(node: t.Node): string {
  if (node.type === 'StringLiteral') return node.value
  if (node.type === 'NumericLiteral') return String(node.value)
  return code.slice(node.start ?? 0, node.end ?? 0)
}

const groups: [string, { name: string; value: string; doc: string }[]][] = []
for (const s of ast.program.body) {
  if (s.type !== 'ExportNamedDeclaration' || s.declaration?.type !== 'VariableDeclaration') continue
  for (const d of s.declaration.declarations) {
    const call = d.init
    if (d.id.type !== 'Identifier' || call?.type !== 'CallExpression') continue
    if (call.callee.type !== 'MemberExpression') continue
    const fn = call.callee.property
    if (fn.type !== 'Identifier' || (fn.name !== 'defineVars' && fn.name !== 'defineConsts')) continue
    const obj = call.arguments[0]
    if (obj?.type !== 'ObjectExpression') continue
    groups.push([
      d.id.name,
      obj.properties.flatMap((p) =>
        p.type === 'ObjectProperty' && p.key.type === 'Identifier'
          ? [{ name: p.key.name, value: value(p.value), doc: doc(p) }]
          : []
      )
    ])
  }
}

// Every group is emitted, displayed or not: one named export each, so the
// bundler drops the ones the page never imports.
const out = `// Generated by packages/web/scripts/tokens.ts from the defineVars and defineConsts in packages/uikit/tokens.stylex.ts. Do not edit.

/** One kit token: its key, the literal it is written as, and the comment above it when there is one. */
export type Token = { name: string; value: string; doc: string }

${groups.map(([name, list]) => `export const ${name}: Token[] = ${JSON.stringify(list, null, 2)}`).join('\n\n')}
`
writeFileSync(fileURLToPath(new URL('../src/generated/tokens.ts', import.meta.url)), out)
const total = groups.reduce((n, [, list]) => n + list.length, 0)
console.log(`tokens: ${groups.length} groups, ${total} tokens → src/generated/tokens.ts`)
